name: text_field_validation
description: "A Flutter project for creating and managing text field validations with ease."
version: 1.1.4
repository: "https://github.com/JhonaCodes/text_field_validation"
homepage: https://jhonacode.com

environment:
  sdk: '>=3.4.3 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true