name: text_field_validation
description: "A Flutter project for creating and managing text field validations with ease."
version: 1.0.0
repository: "https://github.com/JhonaCodes/text_field_validation"
homepage: https://jhonacode.com

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
  test: ^1.24.3

flutter: