name: text_field_validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: |
          dart test | tee test_output.txt
          if grep -q "All tests passed!" test_output.txt; then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1
          fi

