name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          # Temporary
          # flutter-version: '3.10.6'
          channel: 'stable'
      - run: |
          # Export envs that get compiled in
          flutter pub get
          TEST_NO_LOGS=1 flutter test
