name: Dart CI && Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install dart dependencies
        run: dart pub get
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Run tests dart
        run: dart test
      - name: Run tests flutter
        run: flutter test
